GET http://localhost:3000/users/videos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjksImlhdCI6MTYwMzA4NDE1NiwiZXhwIjoxNjA1Njc2MTU2fQ.Q11fiMxD4scbs55fIx5_JWOIAskAetILdYK1ZeB6obE
Content-Type: application/json
