DELETE http://localhost:3000/videos/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjksImlhdCI6MTYwMzgxOTUwNCwiZXhwIjoxNjA2NDExNTA0fQ.Iw29FQpcfMq7WyXlv8LTDuc1gAE75W3Eh2IYxalYAFM
Content-Type: application / json